baseURL = "https://pasporty.netlify.app"
defaultContentLanguage = "cs"
title = "Příklady dobré praxe"
disableKinds = ["taxonomyTerm", "taxonomy"]
relativeurls = true

[markup.goldmark.renderer]
unsafe = true
