baseURL = "https://pasporty.netlify.com"
defaultContentLanguage = "cs"
title = "Příklady dobré praxe"
disableKinds = ["taxonomyTerm", "taxonomy"]
relativeurls = true

[blackfriday]
  fractions = false
