backend:
  name: git-gateway
  branch: master
media_folder: static/media
public_folder: /media
display_url: "https://pasporty.netlify.app"
slug:
  encoding: ascii
  clean_accents: true
collections:
  - name: pasporty
    label: Příklady dobré praxe
    label_singular: "Pasport"
    folder: content/pasport
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    preview_path: "pasport/{{slug}}"
    extension: md
    create: true
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        required: false
        widget: string
      - label: Pořadové číslo
        name: number
        required: false
        widget: number
      - label: Připraveno k publikování
        name: ready
        widget: boolean
      - label: Lokalita
        name: title2
        required: false
        widget: string
      - label: Podtitulková otázka
        name: subtitle
        required: false
        widget: string
      - label: Ilustrační příběh
        name: story
        required: false
        widget: markdown
      - label: Analýza
        name: analysis
        required: false
        widget: markdown
      - label: Návrh
        name: design
        required: false
        widget: markdown
      - label: Konkrétní realizace v Brně
        name: solution
        required: false
        widget: markdown
      - label: Omezení řešení
        name: constraints
        required: false
        widget: markdown
      - label: Závěry
        name: conclusion
        required: false
        widget: markdown
      - label: Ilustrace před
        name: before
        required: false
        widget: object
        fields:
          - label: "Obrázek"
            name: "name"
            required: false
            widget: "image"
          - label: "Zdroj obrázku"
            name: source
            widget: string
          - label: "Popis obsahu obrázku"
            name: alt
            required: false
            hint: "Alternativa pro zrakově postižené čtenáře"
            widget: string
      - label: Ilustrace po
        name: after
        required: false
        widget: object
        fields:
          - label: "Obrázek"
            name: "name"
            required: false
            widget: "image"
          - label: "Zdroj obrázku"
            name: source
            widget: string
          - label: "Popis obsahu obrázku"
            name: alt
            required: false
            hint: "Alternativa pro zrakově postižené čtenáře"
            widget: string
      - label: Časová osa
        name: timeline
        required: false
        widget: list
        collapsed: false
        fields:
          - label: Časové ukotvení (nejčastěji rok)
            widget: string
            name: time
            required: false
          - label: Popis
            widget: string
            name: name
            required: false
          - label: Relativní délka (číslo > 1)
            widget: number
            name: parts
            required: false
            default: 1
            hint: Nejkratší segment má 1, ostatní mají násobky.
      - label: Slovníček
        name: dictionary
        required: false
        widget: relation
        multiple: true
        collection: dictionary
        searchFields: [title]
        valueField: title
      - label: Odkazy na rozšiřující materiály
        name: links
        required: false
        widget: list
        collapsed: false
        fields:
          - label: Odkaz
            name: link
            widget: string
          - label: Popis odkazu
            name: description
            widget: string
  - name: dictionary
    label: Slovníček
    label_singular: "Heslo"
    folder: content/dict
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    preview_path: "dict/{{slug}}"
    extension: md
    create: true
    editor:
      preview: false
    fields:
      - { label: Název hesla, name: title, widget: string }
      - label: Status
        name: status
        default: příprava
        widget: select
        options: ["příprava", "napsáno", "hotovo"]
      - {
          label: Velmi krátká definice (uvnitř pasportu),
          name: short,
          widget: text,
        }
      - { label: Definice (kniha), name: body, widget: markdown }
