backend:
  name: git-gateway
  branch: master
media_folder: static/media
public_folder: /media
display_url: "https://pasporty.netlify.com"
slug:
  encoding: ascii
  clean_accents: true
collections:
  - name: pasporty
    label: Příklady dobré praxe
    label_singular: "Pasport"
    folder: content/pasport
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    preview_path: "pasport/{{slug}}"
    extension: md
    create: true
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        required: false
        widget: string
      - label: Lokalita
        name: title2
        required: false
        widget: string
      - label: Podtitulek
        name: subtitle
        required: false
        widget: string
      - label: Ilustrační příběh
        name: story
        required: false
        widget: markdown
      - label: Analýza
        name: analysis
        required: false
        widget: markdown
      - label: Návrh
        name: design
        required: false
        widget: markdown
      - label: Konkrétní realizace v Brně
        name: solution
        required: false
        widget: markdown
      - label: Omezení řešení
        name: constraints
        required: false
        widget: markdown
      - label: Závěry
        name: conclusion
        required: false
        widget: markdown
      - label: Ilustrace před
        name: before
        required: false
        widget: object
        fields:
          - label: "Obrázek"
            name: "name"
            required: false
            widget: "image"
          - label: "Popis obsahu obrázku"
            name: alt
            required: false
            hint: "Alternativa pro zrakově postižené čtenáře"
            widget: string
      - label: Ilustrace po
        name: after
        required: false
        widget: object
        fields:
          - label: "Obrázek"
            name: "name"
            required: false
            widget: "image"
          - label: "Popis obsahu obrázku"
            name: alt
            required: false
            hint: "Alternativa pro zrakově postižené čtenáře"
            widget: string
      - label: Časová osa
        name: timeline
        required: false
        widget: list
        collapsed: false
        fields:
          - label: Časové ukotvení (nejčastěji rok)
            widget: string
            name: time
            required: false
          - label: Popis
            widget: string
            name: name
            required: false
          - label: Relativní délka (číslo > 1)
            widget: number
            name: parts
            required: false
            default: 1
            hint: Nejkratší segment má 1, ostatní mají násobky.
      - label: Slovníček
        name: dictionary
        required: false
        widget: select
        multiple: true
        options:
          - oprava
          - rekonstrukce
          - indukční smyčka
          - reliéfní dlažba
          - naváděcí dlažba
          - signální dlažba
          - vodicí pes
          - asistenční pes
          - označník
          - bezbariérové nástupiště
        hint: Slovníček zatím není provázaný se stránkami.
  - label: Seznamy
    name: lists
    editor: { preview: false }
    files:
      - label: Slovníčková hesla
        name: dictionary
        required: false
        editor: { preview: false }
        file: data/dictionary.yml
        fields:
          - label: Heslo
            name: dict
            widget: list
            fields:
              - { label: Název hesla, name: name, widget: string }
              - { label: Definice, name: definition, widget: markdown }
